# -*- coding: utf-8 -*-
"""Nattapong Panthiya - Lab 2_Hello World.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1OCGtCRzMpinQF8RaBAwR0pXFceWRDvkF

# ฟังก์ชัน print() ใน Python

ฟังก์ชัน print() ใช้ในการพิมพ์ข้อความที่ระบุลงบนหน้าจอหรืออุปกรณ์แสดงผลมาตรฐานอื่น ๆ ข้อความสามารถเป็นสตริง (String) หรือวัตถุอื่น ๆ โดย วัตถุจะถูกแปลงเป็นสตริงก่อนที่จะเขียนลงบนหน้าจอ

## สอนคอมพิวเตอร์ให้พูดว่า "Hello World"

![alt text](https://images.unsplash.com/photo-1532568547949-a09f1afe4d1b?ixlib=rb-0.3.5&ixid=eyJhcHBfaWQiOjEyMDd9&s=c60f91260b7f8e07e067794735d0cf22&auto=format&fit=crop&w=500&q=60)

เรียนภาษาไหน ก็ต้องเจอ Hello World วันนี้ก็เช่นกัน 555+

ใน Python เราใช้ฟังชั่น print( ) เพื่อสั่งให้คอมพิวเตอร์พูดคำที่เราต้องการ

ลองกดรัน Cell ด้านล่าง (กดปุ่ม **SHIFT + ENTER** พร้อมกัน)
"""

print("Hello world")

# ข้อความหรือ text ที่เราอยากให้มันพูดต้องอยู่ในเครื่องหมาย " " (double quote) หรือ ' ' (single quote)
# แสดง ข้อความ She said. 'I'll go shopping with you.'
print('She said. \'I\'ll go shopping with you.\'')
print("He said. \"Python for Non-Programmer\"")
print('He said. "Python for Non-Programmer"')
print("จะ single quote หรือ double quote ก็ปริ้นได้เหมือนกัน")

# ลองสั่งให้พิมพ์ชื่อของคุณ
print("ณัฐพงษ์ ปันธิยะ")

# เราสามารถสั่งปริ้นแบบขึ้นบรรทัดใหม่ได้ง่ายๆ ด้วยการใส่ \n ไปในข้อความของเรา
# \n แปลว่าขึ้นบรรทัดใหม่ !! มาลองดูตัวอย่าง

print("line one\nline two\nline three")

# ง่ายอะไรเบอร์นี้
# Python version 3 ที่เรากำลังเรียนกันอยู่รองรับ Unicode คืออ่านภาษาไทยได้ด้วย

print("ภาษาไทยเราก็อ่านออกจ้าาาาา")

# print หลายข้อความในคำสั่งเดียว
print("Hello,","how are you?","I am good!!!")

# print แบบระบุสิ่งที่จะพิมพ์ในตอนท้าย
print("Hello,", "how are you?","I am good!!!", end='\t\t')
print("เว้นระยะห่างกันสักหน่อย")

# print แบบกำหนดตัวคั่น (seperator)
print("Hello,", "how are you?","I am good!!!", sep="???")

# print ตัวแปรแบบ tuple
# Tuple คือ ชนิดข้อมูลที่ในหนึ่งตัวแปรสามารถเก็บค่าได้หลาย ๆ ค่า

x = ("apple", "banana", "cherry")
print(x)

"""## Summary
และนี่คือการเขียนโค้ดครั้งแรกของคุณเลยใน Python สั่งงานให้คอมพิวเตอร์พูดได้ง่ายๆด้วย ฟังก์ชัน print()
"""

# แบบฝึกหัด
# ให้พิมพ์ข้อความต่อไปนี้ "The greatest glory in living lies not in never falling, but in rising every time we fall." - Nelson Mandela
print("\"The greatest glory in living lies not in never falling, but in rising every time we fall.\" - Nelson Mandela")

# ให้พิมพ์คำแปลเป็นภาษาไทยของข้อความด้านบน
print("\"เกียรติยศสูงสุดของการมีชีวิตอยู่ ไม่ได้อยู่ที่การไม่เคยล้ม แต่คือการลุกขึ้นทุกครั้งที่ล้มลง\"— เนลสัน แมนเดลา")