# -*- coding: utf-8 -*-
"""Nattapong Panthiya - Lab 17_Intro to Pandas.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1yXV5JI5jfPz8gMbwzfsg0EXKt7c0JYkT

## Pandas DataFrame

![alt text](https://images.unsplash.com/photo-1532458198880-add09ce3b2f5?ixlib=rb-0.3.5&ixid=eyJhcHBfaWQiOjEyMDd9&s=eb5e0a53a108eede9e2767a8539d367c&auto=format&fit=crop&w=500&q=60)

**pandas** คือ ไลบรารีใน Python ที่ใช้สำหรับทำงานกับชุดข้อมูล (data sets) สร้างขึ้นโดย [Wes McKinney](http://wesmckinney.com/) ผู้แต่งหนังสือ **Python for Data Analysis**

tutorial นี้เราจะมาทำความรู้จักว่า pandas ทำอะไร และใช้งานอย่างไร

ก่อนจะใช้งาน pandas ได้ ต้อง import มันเข้า notebook เราก่อนด้วย syntax

```
    import pandas as pd
```

# ข้อดีของ pandas

pandas ช่วยให้เราสามารถวิเคราะห์ข้อมูลขนาดใหญ่และสรุปผลตามทฤษฎีทางสถิติ

pandas สามารถทำความสะอาดชุดข้อมูล และทำให้ชุดข้อมูลอ่านง่าย สะดวกต่อการนำไปประมวลผลต่อ
"""

## we normally import pandas and np together

import pandas as pd
import numpy as np

## create dictionary

dict_data = {
    'year': [2015, 2016, 2017, 2018, 2019, 2020, 2021, 2022],
    'population': [10000, 20000, 30000, 40000, 45000, 50000, 55000, 80000],
    'country': ['Thailand', 'UK', 'Japan', 'America', 'Vietnam', 'Korea', 'China', 'Brazil']
}

"""# ดาต้าเฟรม (DataFrames)
ชุดข้อมูลใน Pandas เรียกว่า DataFrames เป็นโครงสร้างข้อมูล 2 มิติ เช่น อาร์เรย์ 2 มิติ หรือตารางที่มีแถวและคอลัมน์
"""

## create DataFrame using pandas
df = pd.DataFrame(dict_data, columns = ['year', 'country', 'population'])

## print DataFrame
print(type(df))
df

"""| calories | duration   |
|----------|------------|
| 420      | 50         |
| 380      | 40         |
| 390      | 45         |

## แบบฝึกหัด
"""

# ลองสร้าง DataFrame สำหรับเก็บข้อมูลตามตารางด้านบน
# import pandas เข้ามา
import pandas as pd


# สร้าง dictionary โดยมี key เป็นชื่อคอลัมน์ และมี value เป็น list ของค่าในแต่ละแถวของคอลัมน์นั้น
dictionary = {
    'calories': [420, 380, 390],
    'duration': [50, 40, 45]
}

# สร้าง DataFrame โดยใช้ pandas โดยตั้งชื่อ dataframe ว่า df2
df2 = pd.DataFrame(dictionary, columns = ['calories', 'duration'])

# แสดง DataFrame
print(type(df))
df2

"""### useful function/ method with dataframe

- df.info()
- df.head()
- df.tail()
- df.describe()
- df.plot()
"""

# DataFrame information"
df.info()

# print first 5 rows
df.head()

# print last 5 rows
df.tail()

# summary statistics
df.describe()

"""### เราสามารถดึงข้อมูลบางคอลัมน์ออกมาเก็บไว้ได้

วิธีการเลือกคอลั่มของ pandas ทำได้สองแบบ
- df.column_name
- df['column_name']
"""

# how to select column from DataFrame
pop1 = df.population
pop2 = df['population']

print(pop1)
print(pop2)

"""### เราสามารถ slice DataFrame ได้ด้วย .loc()

```
df.loc[rows, columns]
```
"""

# slice dataframe
df.loc[0:4, ["population", "country", "year"]]

"""# อ่านข้อมูลจากไฟล์มาเก็บใน DataFrame

หากชุดข้อมูลของคุณจัดเก็บไว้ในไฟล์ เราสามารถใช้ Pandas ในการดึงข้อมูลจากไฟล์มาใส่ลงใน DataFrame ได้
"""

import pandas as pd

df3 = pd.read_csv('/content/sample_data/california_housing_test.csv')

df3

"""### ใช้ numpy เพื่อวิเคราะห์ข้อมูลอย่างรวดเร็ว

วิธีการเขียน numpy + pandas หาค่าสถิติง่ายๆ ทำได้สองแบบ

- np.mean(df.column)
- df.column.mean()
"""

# basic statistics using numpy
print(np.mean(df.population))
print(df.population.mean())

print(np.mean(df['population']))
print(df['population'].mean())

print(np.sum(df.population))
print(df.population.sum())

"""### Summary

pandas คือ ไลบรารีใน Python ที่ใช้จัดการ dataframe ได้อย่างมีประสิทธิภาพ ใช้คู่กับ numpy เราสามารถวิเคราะห์ข้อมูลได้เร็วขึ้นมาก

"""