# -*- coding: utf-8 -*-
"""Nattapong Panthiya - Lab 5_Variables.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1k_7Lej1GhINnrW2t1e2JqnuAGgItaYjz

## Variables



การสร้างตัวแปรใน Python ใช้แค่เครื่องหมาย = ได้เลย แบบนี้

```
x = 100
y = 200
income_this_year = 25000
income_next_year = 35000
```

**กฎการตั้งชื่อตัวแปรใน Python**

*   ต้องขึ้นต้นด้วยตัวอักษรหรือ underscore (_)
*   ห้ามขึ้นต้นด้วยตัวเลข
*   ใช้ได้เฉพาะอักขระที่เป็นตัวอักษร ตัวเลข และขีดล่างเท่านั้น (A-z, 0-9, _ )
*   เป็น case-sensitive (age Age และ AGE เป็นตัวแปรสามตัวที่ต่างกัน)
*   ห้ามใช้ reserved words ในการตั้งชื่อ เช่น if, else, for, while ฯลฯ


**การตั้งชื่อตัวแปรที่ดี ให้ตั้งชื่อแบบนี้**


*   ใช้ตัวพิมพ์เล็ก lower-case
*   ถ้าชื่อยาวให้เชื่อมด้วย _

Optional - ดู reserved words ทั้งหมดได้[ที่นี่](https://docs.python.org/2.5/ref/keywords.html)
"""

# จงคำนวณหา saving เงินออมของเราว่าเดือนนึงจะเหลือเงินออมเท่าไร?
# สร้างตัวแปร income, food_expense, travel
income = 10000
food_expense = 5000
travel = 3000

saving = income - food_expense - travel
print("เงินออมต่อเดือน")
print(saving)

# ถ้าเราเก็บเงินครบ 1 ปี (12 เดือน) จะมีเงินเท่าไร?
yearly_saving = 3000

yearly_saving = saving * 12
print("ฝากครบหนึ่งปี เราจะมีเงินออมเท่ากับ")
print(yearly_saving)

# ถ้าเราฝากเงินก้อนนี้ไปอีก 10 ปี ดอกเบี้ยปีละ 15% ทบต้น
# เงินฝากของเราจะเป็นเท่าไร?
# ลองคำนวณได้ง่ายๆดวยสูตรดอกเบี้ยทบต้น FV = PV*(1+interest)**year

FV = yearly_saving * ((1+0.15) ** 10)
print("ฝากเงินก้อนนี้ไปอีก 10 ปี ได้ดอกเบี้ยปีละ 15% เงินออมของเราจะเพิ่มขึ้นเป็น")
print(FV)

"""## Test Your Knowledge
ในหนึ่งวันมีเวลากี่วินาที ลองคำนวณได้ใน cell ถัดไป
"""

# แบบฝึกหัด
# total seconds in one day
# ตั้งตัวแปรตามความเหมาะสม

seconds = 60 * 60
total_seconds_day = seconds * 24

print(f"หนึ่งวันมี {total_seconds_day} วินาที")

"""## Summary
สรุป เราสามารถสร้างตัวแปรใน Python ด้วยเครื่องหมาย = เวลาตั้งชื่อก็ตั้งให้อ่านง่ายๆ ตามกฏที่เราแนะนำวันนี้นะครับทุกคน

EP6 ตอนต่อไปเราจะมาอธิบายเรื่อง Data Types ให้เข้าใจกันเอง
"""

# ตัวแปร (variable) สามารถเก็บข้อมูลได้หลายแบบ หลักๆคือตัวเลข (int/float)
# ตัวอักษร/ข้อความ (string) และ True/False (bool)
# เราสามารถตรวจสอบ data types ได้ด้วยฟังชั่น type()

x = 100
print(type(x))

y = 2.46
print(type(y))

z = True
print(type(z))

k = "Ronaldo"
print(type(k))