# -*- coding: utf-8 -*-
"""แบบฝึกหัดครั้งที่4.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1lS6OE8Z_WHH4U95-wrvBZv0MobTfLNtA
"""

x = range(1,10)
if 10 not in x :
  print("เลข 10 ไม่อยู่ในช่วงที่กำหนด")
else:
  print("เลข 10 อยู่ในช่วงที่กำหนด")

"""1. ให้เขียนโปรแกรมแสดงชื่อ-นามสกุลนักศึกษาจำนวน 5 ครั้งด้วยลูป for"""

name = "Nattapong Panthiya"

for name in range(0,5):
  print("Nattapong Panthiya")

"""2. ให้เขียนโปรแกรมแสดงตัวเลข 1 ถึง 10 โดยใช้ลูป for"""

for i in range(1,10,2):
  print(i)

"""3. ให้เขียนคำสั่งแสดงผลดังผังงานต่อไปนี้"""

sum = 0
for num in range(1,51):
  sum = sum + num
print(sum)

for num in range(1, 11, 2):
    print(num)
print("good bye")

mul = 0
for i in range(1,13):
  mul = 2 * i
  print(mul)

"""4. ให้เขียนคำสั่งแสดงผลดังผังงานต่อไปนี้"""

i = 1
while i <= 9:
  print("Happy Day")
  i = i + 1
print("good Bye")

i = 9
while i > 0:
  print("Happy Day")
  i = i - 1
print("Good Bye")

ch = 'n'
while ch != 'y':
    ch = input("ch : ")
print("Good Bye")

num = 1
sum = 0

while num <= 50:
  sum = sum + num
  num = num + 1
print(sum)

sum = 0
avg = 0
count = 1

while count <= 5:
    num = int(input("Enter number %d : " % count))
    sum = sum + num
    count = count + 1

avg = sum / 5
print("Sum = %d /n Avg = %d" % (sum, avg))

"""5. ให้เขียนคำสั่งแสดงผลดังผังงานต่อไปนี้"""

for i in range(1, 4):
    for j in range(1, i +1):
        print(i," ", j)

for i in range(1, 10):
    for j in range(1, i +1):
        print("*", end=" ")
    print("\n")

"""6. ให้เขียนโปรแกรมรับแม่สูตรคูณทางแป้นพิมพ์ แล้วแสดงแม่สูตรคูณแม่นั้น ๆ
เช่น
ป้อนแม่สูตรคูณ : 5
5 x 1 = 5
5 x 2 = 10
5 x 3 = 15
"""

x = int(input("Enter Your Wont : "))

for i in range(1,13):
  result = x * i
  print("%d x %d = %d"%(x,i,result))