# -*- coding: utf-8 -*-
"""Nattapong Panthiya - Lab 8_Function VS  Method.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1dF7byUtCgsIb3p6ViK5-YgPguhBBrGQW

## ยัง!! เรายังไม่จบกับ String

tutorial นี้เราจะมาลองเล่นอีกนิดกับ string ว่าเราทำอะไรกับมันได้อีกบ้าง

string ในโลกของ data science เราเรียกว่า **unstructured data** ตัวอย่างเช่น comments, posts, blogs, twitters บนโลก social media เราสามารถดึงข้อมูลพวกนั้นมาทำ data analysis ได้เยอะมาก ถ้าเราทำงานกับ string ได้ดี เราสามารถแก้ปัญหาอะไรได้อีกหลายอย่างเลย

## ทำความรู้จักกับ method ใน Python

เราได้ลองเล่น function กันมาบ้างแล้ว เช่น print( ) กับ len( )

```
course_name = "python for non-programmer"
print(course_name)
len(course_name)
```

ใน Python จะมีฟังชั่นอีกประเภทนึง ที่เราเรียกว่า **method** (เป็นฟังชั่นที่ใช้ได้เฉพาะกับ class นั้นๆ เช่น string เราก็จะเรียก string method)

อ่านงี้แล้วงง? มาลองดูตัวอย่างเด๋วเข้าใจเลย!
"""

course_name = "python for non-programmer"
type(course_name)

# เราสามารถเรียกดู method ของตัวแปร string ได้ง่ายๆด้วยฟังชั่น dir()
# ตัวที่เป็นแบบ __xxx__ ไม่ต้องไปสนใจ ให้เลื่อนลงไปดูข้างล่างได้เลย

dir(course_name)

"""## String Methods ที่สำคัญ

เราสามารถเรียกใช้งานฟังชั่นเฉพาะของ string variable ได้ด้วยการใช้ **.**

ดูตัวอย่างการใช้งานได้ใน cell ข้างล่างเลย

*   str.upper()
*   str.lower()
*   str.capitalize()
*   str.strip()
*   str.count()
*   str.split()
"""

# เปลี่ยนชื่อคอร์สให้เป็น UPPER CASE
course_name.upper()

# เปลี่ยนชื่อคอร์สให้เป็น lower case
course_name.lower()

# capitalize ตัวอักษรตัวแรกของ course_name
course_name.capitalize()

# ลบ white space ที่อยู่ระหว่าง word นั้นๆ
example_word = "  hahaha       "
print(len(example_word))
print(example_word)
print(example_word.strip())
x=example_word.strip()
print(len(x))

# นับ word หรือตัวอักษรที่เราต้องการ
# นับตัวอักษร 'a'
example_word = "aaaaabbbbccccdsdsdseaaa"
example_word.count('aa')

# นับคำว่า 'United' ใน wikipedia ลิ้งนี้
# https://en.wikipedia.org/wiki/Manchester_United_F.C.

text = """Manchester United Football Club, commonly known as Man. United or \
        simply United, is a professional football club based in Old Trafford,\
        Greater Manchester, England, that competes in the Premier League, the \
        top flight of English football. Nicknamed "the Red Devils", the club \
        was founded as Newton Heath LYR Football Club in 1878, changed its name\
        to Manchester United in 1902 and moved to its current stadium, Old\
        Trafford, in 1910. Manchester United have won more trophies than any\
        other club in English football,[3][4] with a record 20 League titles,\
        12 FA Cups, 5 League Cups and a record 21 FA Community Shields. \
        United have also won three UEFA Champions Leagues, one UEFA Europa \
        League, one UEFA Cup Winners' Cup, one UEFA Super Cup, one \
        Intercontinental Cup and one FIFA Club World Cup. In 1998–99, \
        the club became the first in the history of English football to achieve\
        the treble of the Premier League, the FA Cup and the UEFA Champions \
        League.[5] By winning the UEFA Europa League in 2016–17, they \
        became one of five clubs to have won all three main UEFA club \
        competitions, and the only English club to have won every ongoing \
        top-flight honour available to them."""

text.count('United')

# แบบฝึกหัด
# เปลี่ยน text ให้เป็นตัวอักษรตัวพิมพ์เล็กทั้งหมด แล้วนับคำว่า 'football' ว่าปรากฏกี่ครั้ง

print("เปลี่ยน text ให้เป็นตัวพิมพ์เล็กทั้งหมด")
text_lower = text.lower()
print(text_lower)

print("ฟุตบอลมีทั้งหมด")
text.count('football')

# แยกประโยคออกเป็นคำ (split) แบบเร็วๆ
text = "I:am:learning:Python:Programming:with:DataRockie:School"
text.split(':')

############### SUMMARY #################

## ความแตกต่างระหว่าง function vs. method

## function
print("hello world")
print(len("hello world"))
print("")

## method
print("ลองดูความแตกต่างของสามคำนี้")
print("hello world".upper())
print("hello world".capitalize())
print("    hello world      ".strip())

"""## Summary

You are AWESOME !!!

ตอนนี้ทุกคนรู้ความเหมือน และความแตกต่างของ function vs. method แล้ว จริงๆมันก็คือฟังก์ชันทั้งคู่ แต่ method คือฟังชั่นที่เฉพาะเจาะจงกับ class นั้นๆ

ปล. สำหรับ course การเขียนโปรแกรมเบื้องต้น รู้แค่ว่า class ก็คือ object ที่เราสร้างขึ้นมาก็พอ :D

**function(str)** แต่ว่า **str.method( )**

วิธีการเรียกดู method ของ object นั้นๆ แค่พิมพ์ **dir(object)**

# String methods

รายการ method ที่สามารถใช้งานกับ String object สามารถศึกษาเพิ่มเติมได้[ที่นี่](https://www.w3schools.com/python/python_strings_methods.asp)
"""