# -*- coding: utf-8 -*-
"""Nattapong Panthiya - Lab 7_ String.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Q5-FiYip-VD_-R967F1D49S9-ZQM5eu3

## Basic String in Python

วิธีการจัดการ string variable เบื้องต้นใน Python

string คือตัวแปรที่เป็นข้อความ text ทั่วๆไป เช่น "hello world" การประกาศ String ข้อความจะอยู่ในเครื่องหมาย Double quote หรือ Single quote เท่านั้น
"""

# ให้ลองประกาศให้ตัวแปร str1 เก็บข้อความ I'm a student.

str1 = 'I\'m a student'
print(str1)

# ให้ลองประกาศให้ตัวแปร str2 เก็บข้อความ He said "I would learn Python first"
str2 = 'He said "I would learn Python first"'
print(str2)

course_name = "python for non-programmer"

# ตรวจสอบจำนวน character ในตัวแปร course_name ด้วยฟังชั่น len()
len('wasana santiteerakul')

"""## Slicing (สำคัญมาก อ่านตรงนี้สามรอบ!)

เราสามารถดึงตัวอักษรออกจากตัวแปร course_name ได้ง่ายๆ Python เรียกวิธีการดึงค่าออกจากตัวแปรนึงๆว่า **Slice**

![alt text](https://images.unsplash.com/photo-1493882946517-213a21fe70f8?ixlib=rb-0.3.5&ixid=eyJhcHBfaWQiOjEyMDd9&s=ad578cb13da82215e0a1bab627a14284&auto=format&fit=crop&w=500&q=60)

เนื่องจาก String นั้นเกิดจากตัวอักษรหลายๆ ตัวต่อกันจนเกิดเป็น String หรือกล่าวอีกนัยหนึ่งก็คือ String คืออาเรย์ของตัวอักษร ดังนั้นเราจึงสามารถเข้าถึงตัวอักษรตำแหน่งต่างๆ ของ String ได้ผ่านทาง Index ของมัน

index ใน Python จะเริ่มจาก 0 และเราใช้เครื่องหมาย [  ] ในการ Slice ค่าที่ต้องการ

```
x = "data science"

ถ้าอยาก slice "d" ออกมาจากตัวแปร x พิมพ์ x[0]
ถ้าอยาก slice "a" ตัวที่สองออกมาจากตัวแปร x พิมพ์ x[1]

ถ้าอยาก slice "data" ออกมาจากตัวแปร x พิมพ์ x[0:4]
ถ้าอยาก slice "sci" ออกมาจากจากตัวแปร x พิมพ์ x[5:8]
ถ้าอยาก slice "science" ออกมาจากตัวแปร x พิมพ์ x[5:]

ถ้าอยาก slice "e" ตัวสุดท้ายออกมาจากตัวแปร x พิมพ์ x[-1]

เวลาเราเขียน [0:3] --> Python จะ slice index 0 ไปจนถึง 2 (แต่ไม่รวม 3)
เวลาเราเขียน [2:5] --> Python จะ slice index 2 ไปจนถึง 4 (แต่ไม่รวม 5)
```

**มาลอง slice ตัวแปร course_name กันบ้าง**

"""

print(course_name)

# อยากได้ตัว p ตัวแรกที่ index 0
course_name[0]

# อยากได้ตัว y ตัวที่สอง index 1
course_name[1]

# อยากไตัว r ตัวสุดท้าย index -1
course_name[-1]

# อยากได้ตัว e ตัวรองสุดท้าย index -2
course_name[-2]

# อยากได้คำว่า python
# python slice ตั้งแต่ index 0 ไปจนถึง 5 (แต่ไม่รวม 6)
# ภาษาอังกฤษ เราเรียกว่า up to but not include 6 (exclusive)
course_name[0:6]

# อยากได้คำว่า for
course_name[7:10]

# อยากได้คำว่า non
course_name[11:14]

# อยากได้คำว่า programmer
# slice ตั้งแต่ index 15 ไปจนสุดเลย
course_name[15:]

# ให้ กำหนดตัวแปร ชื่อ str2 เก็บข้อความว่า "I love Python"
str2 = "I love Python"

# เขียนคำสั่ง slice คำว่า "love" ออกมาจาก str2 และแสดงผลทางหน้าจอ
substring = str2[2:6]  # เริ่มที่ index 2 ถึงก่อน index 6
print(substring)       # แสดงผลว่า "love"

# เขียนคำสั่ง แสดงข้อความ str2 จากหลังมาหน้า
reversed_str = str2[::-1]
print(reversed_str)

"""## เราสามารถรวม string หลายๆคำเข้าด้วยกันด้วยเครื่องหมาย + (String concatenation)

ใช้เครื่องหมาย + ในการนำ string หลาย ๆ ข้อความ มาต่อกัน
```
greeting = "Hello"
name = "Andy,"
question = "How are you?"

statement = greeting + name + question
print(statement)

```


"""

greeting = "Hello"
name = "Andy,"
question = "How are you?"

statement = greeting + name + question
print(statement)

# เวลาเราเคาะ spacebar เพื่อเว้นช่องว่าง
# ช่องว่างพวกนั้น ก็ถือว่าเป็น string character เหมือนกัน
# ลองพิมพ์ statement ใหม่อีกที

statement = greeting + " " + name + " " + question
print(statement)

"""## Cool Trick !

เวลาเรารวม string เข้าด้วยกัน ต้อง make sure ว่าทุกตัวแปรที่เอามาบวกกัน ต้องเป็น string data type

เราสามารถใช้ฟังชั่น **str()** ในการเปลี่ยน type ของตัวแปรก่อนมารวมกันได้ง่ายๆ
"""

# สร้างตัวแปรส่วนสูง น้ำหนัก อายุ แบบ int
height = 177
weight = 68
age = 29

print(type(height))

# เปลี่ยนตัวแปร height, weight, age ให้เป็น string ก่อนจะปริ้นใน console
# ทบทวน \n คือการขึ้นบรรทัดใหม่ (new line)
print("my height: " + str(height) + "\nmy weight: " + str(weight) + "\nmy age: " + str(age))

# ถ้าเราลืมเปลี่ยนจาก int --> str เวลาสั่ง print() มันจะ error
print("my height: " + str(height)) # ขึ้น error แก้ง่ายด้วยการเปลี่ยน height เป็น str(height)

"""## Summary

![alt text](https://images.unsplash.com/photo-1505869634514-f7b36e883cc4?ixlib=rb-0.3.5&ixid=eyJhcHBfaWQiOjEyMDd9&s=4b8c2117f09ed2e7b51c54fb9a1c8ff3&auto=format&fit=crop&w=500&q=60)

เก่งมากทุกคน !!

จบ Tutorial นี้เราสามารถ slice string ได้แล้ว อย่าลืมว่า Python index เริ่มจากศูนย์

และเวลาเรา slice [1:10] Python จะ slice index 1-9 ให้เรา แต่ไม่รวม 10 !! (up to but not include the last index)

"""

# ก่อนไป Tutorial ต่อไป ลองรันโค้ด cell นี้หน่อย
# output เป็นยังไง?

greeting = "Hello "

greeting_five_time = (greeting * 5) + "!!!"

print(greeting_five_time)

"hi " * 10

# ถ้าเข้าใจเรื่อง slice และการใช้ +
# เราเล่นอะไรกับ string ได้อีกเยอะเลย

print(course_name)

print(course_name[0:6] + " " + "is AWESOME" + "!!!")

"""## Optional: Another Cool Trick for Printing String

เราสามารถใช้ .format( ) เวลาเรา print string ลองดูตัวอย่างการใช้งานด้านล่าง

```
string.format( )
```

เราแทนที่ตัวแปรของเราลงไปใน placeholder { } ของ string ที่เราต้องการได้เลย
"""

height = 177
weight = 68
age = 29
print("Hi, my name is Toy. Height: "+str(height)+", Weight: "+str(weight)+", Age: "+str(age))

print("Hi, my name is Toy. Height: {}, Weight: {}, Age: {}".format(height, weight, age))

fan_page = 55000

print("My fan page at datarockie: {}".format(fan_page))

print("My fan page at datarockie: " + str(fan_page))

# ลองพิมพ์โค้ดใน cell นี้และรัน SHIFT + ENTER เพื่อ print string นี้
# แก้ไขตัวแปร your_name, your_age, your_favourite_food

your_name = "Nattapng Panthiya"
your_age = "21"
your_favourite_food = "Pizza"
my_school = "กศน.อำเภอสันทราย"

mystr ="""My name is {}, and I am {} years old.\nMy favourite food is {}.\n
I am learning Python with {}""".format(your_name, your_age, your_favourite_food, my_school)

print(mystr)