# -*- coding: utf-8 -*-
"""Nattapong Panthiya - Lab 15_Python for Data Science.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1NojBY7n5U5g0v1YWFUvS-Lg0AjFixbaY

## เราใช้ Python ทำงาน Data Science ได้อย่างไร?

![alt text](https://images.unsplash.com/photo-1508830524289-0adcbe822b40?ixlib=rb-0.3.5&ixid=eyJhcHBfaWQiOjEyMDd9&s=377e356cce015c363d123504857f8137&auto=format&fit=crop&w=500&q=60)

Python เป็น general computer language ที่ data scientist นิยมนำไปใช้สร้างโมเดลวิเคราะห์ข้อมูล เนื่องจาก Python มีการพัฒนา library / package ที่เข้ามาช่วยในการทำงานด้าน Data Science ซึ่ง
library / package ที่ใช้ในการทำงานด้าน data science บน Python ตัวหลัก ๆ ประกอบด้วย

- numpy
- pandas
- matplotlib
- scikit learn
- seaborn
- scipy

### วิธีการ import library ที่ใช้ในงาน data science

ก่อนที่เราจะใช้ function ที่อยู่ใน numpy pandas ได้ เราต้อง import ฟังชั่นพวกนั้นเข้ามาใน Python notebook ของเราก่อน

```
import package_name as short_name
```
"""

# load data science package in the first cell (always)
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from sklearn import datasets

# load example data (iris)
iris = datasets.load_iris()
iris

"""### สร้าง dataframe ข้อมูลของเรา"""

from os import defpath
# convert to DataFrame
df = pd.DataFrame(iris.data, columns=list(iris.feature_names))
df

from google.colab import sheets
sheet = sheets.InteractiveSheet(df=df)

# print first five rows
df.head()

# print last five rows
df.tail()

"""### ดูค่า summary statistics ง่ายๆด้วย .describe()"""

# summary statistics
df.describe()

"""### เราสามารถสร้าง chart ง่ายๆด้วย .plot()"""

df.plot(x="sepal  length (cm)", y="sepal  width (cm)", kind="scatter", title="My first scatter plot")

# correlation
np.corrcoef(df["sepal length (cm)"], df["sepal width (cm)"])

"""### Awesome Work !!

นี่แค่เพิ่มเริ่มเท่านั้น Lab16 - Lab17 เราจะแนะนำ numpy และ pandas สอง library หลักสำหรับการทำงาน data science/ data analysis ใน Python
"""