# -*- coding: utf-8 -*-
"""Nattapong Panthiya - Lab 6_Data Types.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1E1wEJr6gZHAbbO2dE27F35esQTHDJPmg

## Data Types
![alt text](https://images.unsplash.com/photo-1523871762770-87bda6d9ab58?ixlib=rb-0.3.5&ixid=eyJhcHBfaWQiOjEyMDd9&s=651c083bb21d6ff0ef6eaa4136cbef56&auto=format&fit=crop&w=500&q=60)


Python มี data types หลัก อยู่ 4 ประเภท

*   **int** - ตัวเลขจำนวนเต็ม เช่น 1 2 3 4 5
*   **float** - ตัวเลขมีทศนิยม เช่น 2.34 5.12 3.4 7.89
*   **string** - ข้อความ ชื่อ เหมือน "hello world"
*   **bool** - True/ False

ตรวจสอบ data types ของตัวแปรได้ง่ายๆด้วยฟังชั่น **type()**
"""

x = 100
y = 2.4
z = "I'm learning Python"
k = False

# ตรวจสอบ data type
print(type(x))
print(type(y))
print(type(z))
print(type(k))

"""## Int vs. Float

int เป็นตัวเลขจำนวนเต็ม ส่วน float เป็นตัวเลขที่มีทศนิยม

ในทางสถิติเราเรียกตัวแปร int ว่า discrete หรือ count // ส่วน float เราเรียกว่า continuous

เราสามารถเปลี่ยน data type ของ variable ระหว่าง int กับ float ด้วยฟังชั่น **int()** และ **float()** ตามลำดับ
"""

# int variable
x = 5
print(x)
print(type(x))

# float variable
y = 5.2
print(y)
print(type(y))

# เปลี่ยน int ให้กลายเป็น float
x = 5
print(type(x))
print(x)

x = float(x)
print(type(x))
print(x)

# เปลี่ยน float ให้กลายเป็น int
# ทศนิยมจะถูกตัดทิ้งไปเลย
y = 6.8
print(y)
print(type(y))

y = int(y)
print(y)
print(type(y))

# ลองกด run code cell นี้ดูฮะ
# 4/2 4/2.0 4.0/2 ได้ผลต่างกันไหม? อันไหนได้ int อันไหนได้ float
print(4//2)
print(4/2.0)
print(4.0/2)

"""## Bool
[George Boole](https://en.wikipedia.org/wiki/George_Boole) เป็นผู้ให้กำเนิด Boolean Algebra ซึ่งเกี่ยวข้องกับค่า True/ False ในการเขียนโปรแกรมนั่นเอง

(เค้าเลยตั้งชื่อ data type นี้ว่า bool ใน Python) ใน Python คือค่า **True / False**

![alt text](https://upload.wikimedia.org/wikipedia/commons/c/ce/George_Boole_color.jpg)

Python และ programming language อื่นๆจะมีการเขียน equality condition
ที่ใช้ตรวจสอบว่าสองฝั่งมีค่าเท่ากัน (น้อยกว่า มากกว่า etc) หรือเปล่า? เช่น **10 - 2 == 8 จริงไหม? **
"""

# == ใช้เทียบสองฝั่งของสมการ
10 - 2 == 8

# เราสามารถใช้เครื่องหมาย == != < > <= >= ได้หมดเลยนะครับ
10 * 2 < 19

# != อ่านว่าไม่เท่ากับ
555 != 55

# Python เป็น case-sentitive ตัวพิมพ์เล็กจะไม่เท่ากับตัวพิมพ์ใหญ่
'A' == 'a'

'hello' == 'hello'

# สร้าง bool variable ง่ายๆ
my_bool = 2 * 2 == 4

print(my_bool)
print(type(my_bool))

"""## True = 1 False = 0

bool variable: True และ False ใน Python จะมีค่าติดตัวมันอยู่ด้วย True = 1 และ False = 0
"""

# สร้างตัวแปร x เก็บค่า True เป็น bool variable
x = True
print(x)
print(type(x))

# เปลี่ยน x ให้กลายเป็น int ด้วย int()
x = int(x)
print(x)
print(type(x))

# เปลี่ยนตัวแปร int ให้กลายเป็น bool ด้วย bool()
x = 0
print(x)
print(type(x))

x = bool(x)
print(x)
print(type(x))

"""## String
เราเห็น string มาเยอะแล้วในตัวอย่างวันนี้ สังเกตง่ายๆ string (หรือข้อความ) จะอยู่ในเครื่องหมายคำพูด double quote (" ") หรือ single quote (' ')
"""

my_favourite_team = 'Arsenal'
print(my_favourite_team)

my_name = "toy"
your_name = 'miranda'

print(type(my_name))
print(type(your_name))

# เราสามารถเปลี่ยนตัวแปรทั้งหมดให้กลายเป็น string ด้วย str()
x = 10000
print(x)
print(type(x))
print(x+3)

x = str(x)
print(x)
print(type(x))
print(x+'3')
x=int(x)
print(x)
print(x+3)

"""## Summary

Data Types ใน Python เบื้องต้นประกอบด้วย int float string bool

ไม่ว่าโมเดลของเราจะยากขนาดไหน หน่วยเล็กที่สุดก็คือ int float string bool อยู่ดี

การเข้าใจ Data Types เป็นพื้นฐานสำคัญของการทำงาน Data Science ด้วย Python

- int()
- float()
- str()
"""

#แบบฝึกหัด
#ให้รับค่าเลขจำนวนทศนิยม 2 จำนวนจากผู้ใช้ จากนั้นให้หาผลบวกของเลข 2 จำนวนดังกล่าว

first_number = float(input("ใส่ค่าแรกของคุณ: "))
second_number = float(input("ใส่ค่าที่สองของคุณ: "))
sum = first_number + second_number
print(f"ผลลัพธ์ของ {first_number} + {second_number} = {sum}")