# -*- coding: utf-8 -*-
"""แบบฝึกหัดครั้งที่ 6.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1on-HUgekodoZeFYliHU-UNaXmk2miS0X

1. ให้เขียนโปรแกรม เพื่อแสดงผลลัพธ์ต่อไปนี้ (โปรแกรมทบทวน)
"""

txt = "The best things in life are free!"
if "free" in txt:
  print(("Yes, 'free' is present"))
else:
  print(("No, 'free' is not present"))

"""2.ให้เขียนโปรแกรมแสดงผลลัพธ์ตัวแปล x y z เมื่อกำหนดให้ดังต่อไปนี้"""

fruits = ["apple","banana", "Cherry"]
x, y, z = fruits
for i in fruits:
  print(i)

"""3. ให้แสดงผลลัพธ์ของเซ็ต โปรแกรมต่อไปนี้

"""

x = {10,20,30,40,50}
y = {1,"One",2,"two"}
l1 = ('a','e','i','o','u')
z = set(l1)
for i in x:
  print(i,end=' ')
print("\n")
for i in y:
  print(i,end=' ')
print("\n")
for i in z:
  print(i,end=' ')

"""4. ให้หาผลลัพธ์ของโปรแกรมต่อไปนี้"""

setA = set('javascript')
setB = set('minecraft')
setC = set('13022547')
print(setA)
print(setB)
print(setC)

"""5. ให้หำผลลัพธ์ของโปรแกรม ต่อไปนี้"""

x = {10,20,30,40,50}
print("จำนวนข้อมูลในเซตทั้งหมด คือ ",len(x))
print("จำนวนตัวเลขในเซตที่มีค่ำมากที่สุด คือ ",max(x))
print("จำนวนตัวเลขในเซตที่มีค่ำน้อยที่สุด คือ ",min(x))
print("ผลรวมข้อมูลทั้งหมดในเซต คือ ",sum(x))
print("ชนิดของตัวแปร x คือ ",type(x))

"""6. กำหนดให้เซต s1 ประกอบด้วย 1,3,5,7,9 ให้เขียนโปรแกรมดังนี้


*   เพิ่มสมำชิก 10 เข้ำไปในเซต
*   ลบสมาชิก 3 ออกจากเซต
*   ลบสมาชิกออกจากเซต 2 ตัว
*   เคลียร์ข้อมูลในเซต


"""

s1 = {1,3,5,7,9}

s1.add(10)
print(s1)

s1.remove(3)
print(s1)

for _ in range (2):
  s1.pop()
print(s1)

s1.clear()
print(s1)

"""7. กำหนดให้เซต s1 และ s2 มีสมาชิกัดนี้
*  s1 = {1,2,3,4,5}
*  s2 = {1,3,5,7,9}

---


ให้หำผลลัพธ์กำร Union, Intersection, Difference

"""

s1 = {1, 3, 5, 7, 9}
s2 = {5, 7, 9, 11, 13}

union_result = s1.union(s2)
print("Union:", union_result)

intersection_result = s1.intersection(s2)
print("Intersection:", intersection_result)

difference_result_s1_minus_s2 = s1.difference(s2)
print("Difference (s1 - s2):", difference_result_s1_minus_s2)

difference_result_s2_minus_s1 = s2.difference(s1)
print("Difference (s2 - s1):", difference_result_s2_minus_s1)

"""8. ให้หำผลลัพธ์ของโปรแกรมต่อไปนี้"""

dict = {1:'One',2:'Two',3:'Three',4:'Four',5:'Five'}
for key in dict:
  print(key)
print('-'*20)

"""9. ให้หำผลลัพธ์ของโปรแกรมต่อไปนี้ (ฟังก์ชัน keys)

"""

dict1 = {1:'One',2:'Two',3:'Three',4:'Four',5:'Five'}

for k in dict1.keys():
  print(dict1[k])
print('-'*20)

for k in dict1:
  print(dict1[k])

"""10. ให้หำผลลัพธ์ของโปรแกรมต่อไปนี้(values)"""

dict1 = {1:'One',2:'Two',3:'Three',4:'Four',5:'Five'}
d1 = dict1.values()
for i in d1:
  print(i)

"""11. ให้หำผลลัพธ์ของโปรแกรมต่อไปนี้ (items)

"""

dict1 = {1:'One',2:'Two',3:'Three',4:'Four',5:'Five'}
for i,j in dict1.items():
  print(i,j)

"""12. ให้หำผลลัพธ์ของโปรแกรมต่อไปนี้ (copy)"""

dict1 = {1:'One',2:'Two',3:'Three',4:'Four',5:'Five'}
dict2 = dict1.copy()
print(dict2)
dict3 = dict1
print(dict3)

"""13. ให้หำผลลัพธ์ของโปรแกรมต่อไปนี้"""

dict1 = {1:'One',2:'Two',3:'Three',4:'Four',5:'Five'}
print(dict1.get(3))
dict1.pop(3)
print(dict1)
dict1.popitem()
dict1.update({1:"หนึ่ง"})
print(dict1)
dict1.clear()
print(dict1)

"""14. ให้เขียนโปรแกรมแบบดิกชันนำรี โดยเก็บรหัสนักศึกษา และชื่อนักศึกษาจำนวน 5 คนแล้ว
แสดงผลลัพธ์ดังนี้

*   ให้แสดงรหัสนักศึกษา และชื่อทุกคน
*   ให้แก้ไขชื่อเพื่อนลำดับที่ 3 เป็นชื่อเล่น แล้วแสดงเฉพาะเพื่อนลำดับที่ 3
*   ให้ลบเพื่อนลำดับที่ 4 ออก แล้วแสดงผลข้อมูลเพื่อนที่เหลือ
*   ให้ลบข้อมูลทั้งหมด แล้วแสดงผลลัพธ์


"""

students = {
    401: 'นายประยุตธ์',
    402: 'นายประวิทย์',
    403: 'นางสาวปารีณา',
    404: 'นายสันธนะ',
    405: 'นายชาดา'
}

print("รหัสนักศึกษา  ชื่อ")
for code, name in students.items():
    print(f"{code}              {name}")

students.update({403:"เอ๋"})
print()
print("แสดงเฉพาะเพื่อนลำดับที่ 3")
print(students.get(403))

students.pop(404)
print()
print("ลบเพื่อนลำดับที่ 4 ")
for code, name in students.items():
    print(f"{code}              {name}")

students.clear()
print()
print("ลบข้อมูลทั้งหมด")
print(students)