# -*- coding: utf-8 -*-
"""Nattapong Panthiya - Lab 3_Basic calculation.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1iv7uuXD5XDdAWHPogzvoP687GfEpAv-h

# ตัวดำเนินการ (Operators) ใน Python

ตัวดำเนินการใช้เพื่อดำเนินการกับตัวแปรและค่าต่าง ๆ เช่น การคำนวณทางคณิตศาสตร์ การเปรียบเทียบค่า เป็นต้น

ในตัวอย่างด้านล่าง เราใช้ตัวดำเนินการ + เพื่อบวกค่าสองค่าเข้าด้วยกัน:
"""

print(10 + 5)

"""ตัวดำเนินการใน Python แบ่งเป็นประเภท ดังนี้


*   Arithmetic operators
*   Assignment operators
*   Comparison operators
*   Logical operators
*   Identity operators
*   Membership operators
*   Bitwise operators

## Python คือเครื่องคิดเลขดีๆนี่เอง

เราสามารถคำนวณเลขง่ายๆได้เลยด้วย Python

*   add
*   subtract
*   multiply
*   division
*   exponent
*   modulo

# ตัวดำเนินการทางคณิตศาสตร์ (Arithmetic operators) ใน Python

| Operator |Name           | Example  |
|:--------:|----------------|:--------:|
| +        |Addition        | x + y    |
| -        | Subtraction    | x - y    |
| *        | Multiplication | x * y    |
| /        | Division       | x / y    |
| %        | Modulus        | x % y    |
| **       | exponentiation | x ** y   |
| //       | Floor Division | x // y   |
"""

# add บวก
print(1 + 1)
print(3 + 8)

# subtract ลบ
print(19 - 9)
print(20 - 3)

# multiply คูณ
print(2 * 5)
print(3 * 3)

# division หาร
print(5 / 2)
print(12 / 4.0)

# exponent ยกกำลัง
print(3 ** 2) # สามยกกำลังสอง
print(4 ** 3) # สี่ยกกำลังสาม

# modulo หรือเรียกสั้นๆว่า mod คือการหารตัวเลขเศษ
# ถ้าหารลงตัวจะได้ค่าศูนย์ ถ้าหารไม่ลงตัว Python จะ return เศษกลับมาให้เรา

print(10 % 3) # สิบหารสาม เหลือเศษ 1
print(5 % 3) # ห้าหารสาม เหลือเศษ 2
print(6 % 2) # หารลงตัว 0

# Floor Divsion หารเอาแต่จำนวนเต็ม
print("10//3 = ",10//3) # สิบหารเอาแต่จำนวนเต็มด้วยสาม ได้ผลลัพธ์ คือ 3
print("5//3 = ",5//3) # ห้าหารเอาแต่จำนวนเต็มด้วยสาม ได้ผลลัพธ์ คือ 1
print("2//3 = ", 2//3) # สองหารเอาแต่จำนวนเต็มด้วยสาม ได้ผลลัพธ์ คือ 0

"""## เราสามารถสร้างการคำนวณที่ซับซ้อนขึ้นได้
ใช้วงเล็บ (  ) เข้ามาช่วยก็ได้ถ้าเกิดการคำนวณเรายาวๆหน่อย
"""

# ตัวอย่าง 1
answer = 100 * 2 + 100 ** 2
print(answer)

# ตัวอย่าง 2
answer = 100 + 2 * 3 ** 3
print(answer)

print("\nอธิบาย:\nเครื่องหมาย ** จะเกิดก่อน * และ +")
print("3 ** 3 = 27 แล้วก็คูณสองได้ 54 แล้วค่อยบวก 100")
print("คำตอบเลยได้เท่ากับ 154")

"""## Summary
Python คือเครื่องคิดเลข เราสามารถ print() ผลลัพธ์ของการคำนวณต่างๆของเราได้ง่ายๆเลย
"""

# แบบฝึกหัด
# เวลา 528790 วินาที คิดเป็น กี่วัน กี่ชั่วโมง กี่นาที และกี่วินาที
result = 528790
days = result // (24 * 3600)
x = result % (24 * 3600)

h = x // 3600
x %= 3600

m = x // 60
s = x % 60

# แสดงผล
print(f"เวลา {result} วินาทีเท่ากับ\n {days} วัน\n {h} ชั่วโมง\n {m} นาที\n {s} วินาที\n")