# -*- coding: utf-8 -*-
"""Nattapong Panthiya - Lab 9 - Control Flow - Conditions if-else.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1InSdGuHmVyLPPZmPvV58h1JcpWuh502t

## Control Flow

มาถึงหัวข้อสำคัญของทุกภาษาในโลกนี้เลย นั่นคือ control flow ที่ใช้ในการควบคุมพฤติกรรมของ program ที่เราเขียน ใน Python หลักๆเราใช้สามแบบ (น้อยมาก เรียนแปปเดียวก็ทำได้แล้ว!!) ประกอบด้วย

*   if-else
*   for loop
*   while loop

tutorial นี้เราจะอธิบาย **if-else** ก่อน (เขียนเหมือนกับ IF ในโปรแกรม Excel เลย)

Alright !! Let's the fun start !!

![alt text](https://images.unsplash.com/photo-1513309914637-65c20a5962e1?ixlib=rb-0.3.5&ixid=eyJhcHBfaWQiOjEyMDd9&s=228f272007b6369007faeba1901c3274&auto=format&fit=crop&w=500&q=60)

## IF ELSE

if-else ใช้สำหรับทดสอบเงื่อนไข ถ้าเงื่อนไขเป็นจริง (True) ให้โปรแกรมทำอย่างนี้ ถ้าเงื่อนไขไม่เป็นจริง (False) ก็ให้โปรแกรมทำอีกอย่างนึง

template สำหรับเขียน if-else ใน Python


```
if True:
    do something
else:
    do something else
```

Python coding style is very **elegant** เมื่อเทียบกับภาษาอื่นๆ คือมันไม่ได้ใช้ปีกกา { } ในการเขียน code block ให้ยุ่งยาก แต่จะใช้การย่อหน้าแทน (**indentation หรือ white space**)

## ตรงนี้สำคัญมาก !!
ย่อหน้า (หรือ white space) ใน Python มีความหมาย โค้ดที่อยู่ในระนาบการย่อหน้าเดียวกัน Python จะเข้าใจว่ามันเป็น block เดียวกัน

มาลองดูตัวอย่างง่ายๆใน cell ด้านล่าง
"""

# Example 1
# ก่อนจะรันโค้ดใน cell นี้
# ลองอ่านโค้ดดูก่อน คิดว่ามันจะปริ้นอะไรออกมาเป็น output?

income = 30000

# simple if-else
if income <= 20000:
    print("You're quite poor!")
else:
    print("You're quite rich!")
    print("ดีจัง")

# Example 2
# ก่อนจะรันโค้ดใน cell นี้
# ลองอ่านโค้ดดูก่อน คิดว่ามันจะปริ้นอะไรออกมาเป็น output?

weather = "rainy"

if weather == "sunny":
  print("Good weather")
else:
  print("Bad weather because it's raining!")

"""## IF ELIF ELSE ทดสอบได้หลาย ๆ เงื่อนไข

เราสามารถใช้ **if, elif, else** keyword ในการสร้างเงื่อนไขที่หลากหลายขึ้นได้

```
if condition1:
    do something
elif condition2:
    do something
elif condition3:
    do something
else:
    do something else
```


"""

# Example 3 -- school grading scheme
# นักเรียนสอบได้คะแนน 0-100
# มาลองตัดเกรดกัน

student_score = 44

# นักเรียนคนนี้ จะได้เกรดอะไร?

if student_score >= 90:
 print("A")
elif student_score >= 80:
  print("B")
elif student_score >= 70:
  print("C")
elif student_score >= 60:
  print("D")
elif student_score >= 50:
  print("E")
else:
  print("Failed")

"""ลองเปลี่ยน student_score และทดลองรันโปรแกรมของเราใหม่ ว่าเกรดเปลี่ยนไหม?

ถ้า student_score = 44 เค้าจะได้เกรดอะไร?

# คำสั่ง if-else แบบบรรทัดเดียว (Short Hand if-else)

ถ้าการทำงานเพียงแค่คำสั่งเดียวทั้งเมื่อเงื่อนไขเป็นจริงและเป็นเท็จในคำสั่ง if-else เราสามารถเขียนคำสั่ง if-else แบบบรรทัดเดียวได้ ดังนี้

```
do-statement1    if   condition-is-true    else  do-statement2
```

เทคนิคนีเรียกว่า การใช้ **Ternary Operators** หรือ **Conditional Expressions**
"""

a = 2000
b = 330
print("A") if a > b else print("B")

# if(a>b)?printf("A"):printf("B"); C language

# สามารถเพิ่มเงื่อนไขหลาย ๆ อัน ในบรรทัดคำสั่งเดียวกันได้ด้วย
a = 330
b = 330
print("A") if a > b else print("=") if a == b else print("B")

"""## Summary

ถ้ามีแค่เงื่อนไขเดียวก็ใช้ if-else ได้เลย

ถ้ามีหลายๆเงื่อนไขก็ใช้ if-elif-else

อย่าลืมว่า indentation / white-space ในโปรแกรม Python มีความหมาย

```
if True:
    do something
else:
    do something else
```

## การฝึกฝนเป็นเรื่องสำคัญ

![alt text](https://images.unsplash.com/photo-1522163182402-834f871fd851?ixlib=rb-0.3.5&ixid=eyJhcHBfaWQiOjEyMDd9&s=a5021bdbd174e54d7ce0e1234c30b523&auto=format&fit=crop&w=500&q=60)

ลองทำโจทย์ข้อนี้ด้วยตัวเอง

มีเมนูอาหารที่เราชอบทาน 4 เมนู
-  weekday breakfast -- **bread and milk**
-  weekday dinner -- **boiled rice**
-  weekend breakfast -- **spaghetti**
-  weekend dinner -- **sukiyaki**

ถ้าวันนี้เป็นวันธรรมดา มื้อเย็น เมนูอาหารของเราคืออะไร?

```
## Hint
today = "weekday"
time = "dinner"

## ใช้ and เข้ามาช่วยสร้างเงื่อนไขได้
if (today == "weekday") and (time == "dinner"):
    print("boiled rice")
elif (today == "weekend") and ("time == breakfast"):
    print("spaghetti")
elif ...:
    print("bread and milk")
else:
    print("sukiyaki")
```
"""

# เขียนโค้ดนี้ให้เต็ม แล้วลองรันเพื่อเช็คคำตอบ
# ลองเปลี่ยน today, time ดูว่าได้คำตอบตรงอย่างที่เราต้องการไหม

today = "weekday"
time = "dinner"

if (today == "weekday") and (time == "dinner"):
  print("My favourite menu: " + "boiled rice")
elif (today == "weekday") and (time == "breakfast"):
  print("My favourite menu: " + "bread and milk")
elif (today == "weekend") and (time=="breakfast"):
  print("My favourite menu: " + "sukiyaki")
else:
  print("My favourite menu: spaghetti")

# แบบฝึกหัด
#เขียนโปรแกรมรับเลขจำนวนเต็ม และตรวจสอบว่าเป็นเลขคู่หรือว่าเลขคี่

number = int(input("ใส่ตัวเลขของคุณ"))

if (number % 2 == 0):
  print("%d ป็นเลขคู่"%number)
else :
  print("%d เป็นเลขคี่")