# -*- coding: utf-8 -*-
"""แบบฝึกหัดครั้งที่ 8.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1-4mzXi-ZlDyeWYClb9YL1jCjukuzpfgx

1. ให้เขียนโปรแกรมแสดงวัน เดือน ปี เกิด ของนักศึกษา
"""

import datetime
year = 2004
month = 2
day = 13
MyBrithday = datetime.date(year, month, day)
print(MyBrithday)

"""2. ให้เขียนโปรแกรมสร้างวันเดือนปีเกิด โดยรับมาทางแป้นพิมพ์"""

import datetime
print("Enter Your Birthday")
day = int(input("Enter Day : "))
month = int(input("Enter Month : "))
year = int(input("Enter Year : "))
YourBrithday = datetime.date(year, month, day)
print(YourBrithday)

"""3. ให้เขียนโปรแกรมเพื่อสร้างเวลา โดยระบุ ชม. นาที วินาที ตามที่ผู้ใช้กำหนด"""

import datetime

def create_custom_time(hours, minutes, seconds):
    try:
        custom_time = datetime.datetime(1, 1, 1, hours, minutes, seconds)

        print("เวลาที่สร้าง:", custom_time.time())

        return custom_time
    except ValueError as e:
        print("ผิดพลาด:", e)

hours = int(input("กรุณาใส่ชั่วโมง: "))
minutes = int(input("กรุณาใส่นาที: "))
seconds = int(input("กรุณาใส่วินาที: "))

custom_time = create_custom_time(hours, minutes, seconds)

"""4. ให้เขียนโปรแกรมหา sin() cos() tan() ระบุตัวเลขที่ต้องการหาเอง"""

import math

def calculate_trigonometric_functions(angle_degree):
    try:
        angle_radian = math.radians(angle_degree)

        sin_value = round(math.sin(angle_radian), 2)
        cos_value = round(math.cos(angle_radian), 2)
        tan_value = round(math.tan(angle_radian), 2)

        print(f"sin({angle_degree}°) =", sin_value)
        print(f"cos({angle_degree}°) =", cos_value)
        print(f"tan({angle_degree}°) =", tan_value)
    except Exception as e:
        print("Error:", e)

angle_degree = float(input("Enter your trigonometric : "))

calculate_trigonometric_functions(angle_degree)

"""5. จากเกมเป่ายิ้งฉุบ ต่อไปนี้ให้ปรับการเล่น จยกว่าฝ่ายใดฝ่ายหนึ่งจะชนะ 3 ครั้งจึงจะตัดสินว่าเป็นฝ่ายชนะ"""

import random

r = ('p', 's', 'h')
com_wins = 0
player_wins = 0

while com_wins < 3 and player_wins < 3:
    com = random.randint(0, 2)
    p = input("ป้อนตัวอักษร {p = กระดาษ s = กรรไกร h = ค้อน} : ")
    print("AI สุ่มได้", r[com])

    if r[com] == p:
        print("เสมอ")
    elif r[com] == 'p' and p == 'h':
        print("ผู้เล่นชนะ")
        player_wins += 1
    elif r[com] == 'h' and p == 's':
        print("ผู้เล่นชนะ")
        player_wins += 1
    elif r[com] == 's' and p == 'p':
        print("ผู้เล่นชนะ")
        player_wins += 1
    else:
        print("AI เล่นชนะ")
        com_wins += 1

if player_wins >= 3:
    print("ผู้เล่นชนะเกม!")
else:
    print("AI เล่นชนะเกม!")