# -*- coding: utf-8 -*-
"""แบบฝึกหัดครั้งที่ 7.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1dxkLhcdC7VokJAM7Z4BLYkO77wdGSBP2

1. ให้เขียนโปรแกรมเพื่อดูผลลัพธ์ต่อไปนี้
"""

def DispNum(num):
  for i in range(1,num+1):
    print(i)

DispNum(5)

"""2. ให้เขียนโปรแกรมเพื่อดูผลลัพธ์ต่อไปนี้"""

def SumNum(num):
  sum = 0
  for i in range(1,num+1):
    sum = sum + i
  print("ผลรวมของตัวเลข 1 ถึง %d เท่ากับ %d" %(num,sum))

SumNum(5)

"""3. ให้เขียนฟังก์ชันชื่อ menu() ละเรียกใช้ฟังก์ชันดังภาพ จากนั้นให้เขียนโปรแกรมเพิ่มเติมโดย


* รอรับค่าจากเมนู
* เขียนฟังก์ชันย่อยชื่อ add() เพื่อบวกเลข 2 จำนวนโดยส่งค่าพารามิเตอร์ไปยังฟังก์ชัน
* เขียนฟังก์ชันย่อยชื่อ sub() เพื่อลบเลข 2 จำนวนโดยส่งค่าพารามิเตอร์ไปยังฟังก์ชัน
* เขียนฟังก์ชันย่อยชื่อ mul() เพื่อคูณเลข 2 จำนวนโดยส่งค่าพารามิเตอร์ไปยังฟังก์ชัน


"""

def menu():
    print("*******************")
    print("Main Menu")
    print("*******************")
    print("A + การบวกเลข")
    print("S - การลบเลข")
    print("M x การคูณเลข")
    print("*******************")

    menu_input = input("Select Menu: ").upper()

    if menu_input == 'A':
        add()
    elif menu_input == 'S':
        sub()
    elif menu_input == 'M':
        mul()
    else:
        print("Please Try Again")

def add():
    print("Add Program")
    add_first = int(input("Enter First Number: "))
    add_second = int(input("Enter Second Number: "))
    result_add = add_first + add_second
    print("%d + %d = %d" % (add_first, add_second, result_add))

def sub():
    print("Sub Program")
    sub_first = int(input("Enter First Number: "))
    sub_second = int(input("Enter Second Number: "))
    result_sub = sub_first - sub_second
    print("%d - %d = %d" % (sub_first, sub_second, result_sub))

def mul():
    print("Mul Program")
    mul_first = int(input("Enter First Number: "))
    mul_second = int(input("Enter Second Number: "))
    result_mul = mul_first * mul_second
    print("%d X %d = %d" % (mul_first, mul_second, result_mul))

menu()

"""4. ให้หาผลลัพธ์จากโปรแกรมที่รับค่าพารามิเตอร์ 2 ค่าดังนี้"""

def Add(num1,num2):
  sum = num1 + num2
  print(" ผลลัพธ์ของการบวกเลข เท่ากับ ",sum)

x = input("ป้อนตัวเลขที่ 1 = ")
y = input("ป้อนตัวเลขที่ 2 = ")
Add(x,y)

"""5.ให้เขียนฟังก์ชันแม่สูตรคูณแบบรับพารามิเตอร์แม่สูตรคูณเข้ามา
แล้วให้ input แม่สูตรคูณจากแป้นพิมพ์แล้วเรียกใช้ฟังก์ชันแม่สูตรคูณเพื่อแสดงผล
"""

def cal(m):

  for i in range(1,13):
    result = x * i
    print("%d x %d = %d"%(m,i,result))

x = int(input("Enter Your Wont : "))
cal(x)

"""6.ให้เขียนโปรแกรมฟังก์ชัน fNum โดยรับค่าพารามิเตอร์มา 1 ตัว จากนั้นตรวจสอบว่าเป็นเลขคู่
หรือเลขคี่

"""

def fNum(x):
  if x % 2==0:
    print(f"{x} เป็นเลขคู่")
  else:
    print(f"{x} เป็นเลขคี่")
y = int(input("Enter Your Number"))
fNum(y)

"""7. ให้เขียนฟังก์ชัน Area สำหรับหาพื้นที่สามเหลี่ยม โดยรับพารามิเตอร์มา 2 จำนวน
โดยตัวเลขทั้ง 2 จำนวนให้ input มาทางแป้นพิมพ์
"""

def Area(b, h):
    result = 0.5 * b * h
    print(f"Result = {result:.2f}")

b = float(input("Enter Your Base: "))
h = float(input("Enter Your Height: "))

Area(b, h)

"""8. ให้หาผลลัพธ์จากโปรแกรมดังนี"""

def sumA(*n):
  a = 0
  for x in n:
    a += x
  print(a)

sumA(3,4,12,1)
sumA(10,20,30)

def printkv(**kv):
  print(type(kv))
  print(kv)

printkv(name='Nattapong', age=20, sex="Male")

"""9.  จากโปรแกรมข้อ 8 ก่อนที่จะทำคำสั่งบรรทัดที่ 7 ให้รับค่าตัวเลขจากแป้นพิมพ์ 3 จำนวน แล้วส่งค่าไปหาผลรวมและค่าเฉลี่ย (ตัดบรรทัดที่ 8 ออก)"""

def sumA(*numbers):
    a = 0
    for x in numbers:
        a += x
    print(a)

number = input("Enter Your Numbers : ")
numbers_list = [int(num) for num in number.split(",")]
sumA(*numbers_list)

"""10. ให้เขียนโปรแกรมเพื่อดูผลลัพธ์ต่อไปนี้"""

def primeNum(num):
  if(num %2 == 0):
    return("เลขคู่")
  else:
    return("เลขคี่")

x = int(input("ป้อนัวเลข : "))
result = primeNum(x)
print("ตัวเลขที่ป้อนเป็น",result)

"""11. ให้เขียนโปรแกรมเพื่อดูผลลัพธ์ต่อไปนี้"""

def Tri(b,h):
  Area = 0.5 * b * h
  return(Area)

x = float(input("Enter Your Base: "))
y = float(input("Enter Your Height: "))
result = Tri(x,y)
print("พื้นที่สามเหลี่ยมเท่ากับ",result)

"""12. ให้เขียนฟังก์ชั่นชื่่อ menu() และเรียกฟังก์ชั้นดังภาพ จากนั้นให้เขียนโปรแกรมเพิ่มเติมโดย
* รอรับค่าจากเมนู
*  เขียนฟังก์ชันย่อยชื่อ add() เพื่อบวกเลข 2 จำนวนโดยส่งค่าพารามิเตอร์ไปยังฟังก์ชัน
* เขียนฟังก์ชันย่อยชื่อ sub() เพื่อลบเลข 2 จำนวนโดยส่งค่าพารามิเตอร์ไปยังฟังก์ชัน
* เขียนฟังก์ชันย่อยชื่อ mul() เพื่อคูณเลข 2 จำนวนโดยส่งค่าพารามิเตอร์ไปยังฟังก์ชัน
"""

def menu():
    print("*******************")
    print("Main Menu")
    print("*******************")
    print("A + การบวกเลข")
    print("S - การลบเลข")
    print("M x การคูณเลข")
    print("*******************")

    menu_input = input("Select Menu: ").upper()

    if menu_input == 'A':
        frist_num = int(input("Enter First Number: "))
        second_num = int(input("Enter Second Number: "))
        result = add(frist_num, second_num)
        print(f"Result: {result}")
    elif menu_input == 'S':
        frist_num = int(input("Enter First Number: "))
        second_num = int(input("Enter Second Number: "))
        result = sub(frist_num, second_num)
        print(f"Result: {result}")
    elif menu_input == 'M':
        frist_num = int(input("Enter First Number: "))
        second_num = int(input("Enter Second Number: "))
        result = mul(frist_num, second_num)
        print(f"Result: {result}")
    else:
        print("Please Try Again")

def add(frist_num, secon_num):
    result_add = frist_num + secon_num
    return result_add

def sub(frist_num, secon_num):
    result_sub = frist_num - secon_num
    return result_sub

def mul(frist_num, secon_num):
    result_mul = frist_num * secon_num
    return result_mul

menu()