# -*- coding: utf-8 -*-
"""สอบ.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1U0X2H9af3mH0UKD0p4oBwm_mspg2xeT5

1. ให้เขียนโปรแกรมรับเลขจำนวนเต็มมา 2 จำนวน จากนั้น ให้เปรียบเทียบว่าตัวเลขใดมากกว่ากัน ดังนี้
"""

x = int(input("Enter First Number : "))
y = int(input("Enter Second Number : "))

if x > y:
  print("Result %d is Greater than %d" %(x,y))
elif y > x:
  print("Result %d is Greater than %d" %(y,x))

x = float(input("Enter your cm. : "))

inches = x / 2.54
foot = inches / 12
print("ตัวเลขเซนติเมตร %.2f เซนติเมตร เท่ากับ %.2f" %(x, foot))