# -*- coding: utf-8 -*-
"""แบบฝึกหัดครั้งที่ 2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1hdbpiskNypIruY4R9qVAnCD58lvK6quT

1. ให้เขียนคำสั่งแสดงผลดังผังงานต่อไปนี้
"""

grade = 3.75
print("Grade = ",grade)

name = "Computer"
print(name)

num1 = 10
num2 = 30
sum = num1 + num2
print(num1)
print(num2)
print("%d + %d = %d"%(num1,num2,num1+num2))
print("ผลบวกของ",num1, " + ", num2, " = ", sum)

"""2. ให้เขียนโปรแกรมต่อไปนี้"""

a = " Hello... \n Python Programing"
print(a)

a = "ยินดีต้อนรับเข้าสู่"
b = "\t\"โปรแกรมภาษาไพธอน \""
print(a)
print(b)

a = "ยินดีต้อนรับเข้าสู่"
b = "\t\"โปรแรกมภาษาไพธอน\""
print("สวัสดีครับ %s" %a)
print("****%s****"%b)

x = 10
y = 20
z = x + y
print("%d + %d = %d"%(x,y,z))

dept = "Computer" "Department"
print(dept)
U1 = "Chiang Mai"
U2 = "Rajabhat"
U3 = "University"
cmru = U1+''+U2+''+U3
print(cmru)

"""3. ให้เขียนโปรแกรมรับค่าข้อมูลต่อไปนี้"""

sub = input("Enter Subject = ")
sec = input("Enter Section = ")
grade = input("Enter Grade = ")
avg = input("Enter Avg. = ")

name = input("Enter Your Name : ")
lname = input("Enter Your LastName")
print("Name %s LastName %s "%(name,lname))

w = float(input("Enter Your W : "))
i = float(input("Enter Your I : "))
area = w*i
print("พื้นที่%.2f X %.2f = %.2f"%(w,i,area))

n1 = int(input("Enter Your Number1 : "))
n2 = int(input("Enter Your Number2 : "))
sum = n1 + n2
print("ผลลัพธ์การบวกของ %d + %d = %d"%(n1,n2,sum))

"""4. แก้ไขโปรแกรมต่อไปนี้ให้ถูกต้อง"""

x = int(input("number1 : "))
y = int(input("number2 : "))
z = x+y
print(z)

x = int(input("number1 : "))
z = 2* x + 1
print(z)

x = int(input("number 1 : "))
z = 2 * x +1
print(z)