# -*- coding: utf-8 -*-
"""แบบฝึกหัดครั้งที่ 3 .ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1DkRhCxyq810tN4fHHCdaVeJjoSxo6EQo
"""

print("welcom...")
print("python programming")

x = "abcd"
type (x)

"""1.ให้เขียนคำสั่งแสดงผลดังผังงานต่อไปนี้"""

score = 80
if score == 80:
  print("Very Good")
else:
  print("Sorry")

score = 85
if score >= 80:
  print("เก่งมาก ๆ ครับ")
print("Good bye")

"""2.ให้เขียนคำสั่งแสดงผลดังผังงานต่อไปนี้"""

x = int(input("Enter Your X : "))
y = int(input("Enter Your Y : "))

if y == 0:
  print("ตัวเลขที่เป็น 0 ไม่สามารถนำมาเป็นตัวหารได้")
else:
  print("%d / %d = %.2f"%(x,y,x/y))
print("Good Bye")

score = int(input("Enter Your Score : "))
if score >= 80:
  print("Your Socre = ",score ,"Very Good")
else:
  print("Good Bye")

"""3.จงเขียนโรปแกรมให้รับค่าตัวเลขจำนวนเต็มมา 1 จำนวน แล้วแสดงผลลัพธ์ตามเงื่อนไขต่อไปนี้"""

number = int(input("Enter Your Number : "))

if number > 0:
  print("Positive Number")
elif number < 0:
  print("Negative Number")
else:
  print("Zero Number")

"""4. จงเขียนโปรแกรม ให้รับเงินเดือนพนักงาน และค่าล่วงเวลา แล้วคำนวณหาภาษีที่ต้องจ่าย และ คำนวณรายได้สุทธิที่พนักงานจะได้รับหลังจากหักภาษีแล้ว โดยเงื่อนไขการคิดภาษีเป็นดังนี้
- ถ้ารายได้รวม น้อยกว่าหรือเท่ากับ 5000 บาท ไม่ต้องคิดภาษี
- ถ้ารายได้รวม อยู่ระหว่าง 5001 - 20000 บาท ให้คิดภาษี 7%
- ถ้ารายได้รวม อยู่ระหว่าง 20001 - 50000 บาท ให้คิดภาษี 10%
- ถ้ารายได้รวม มากกว่า 50000 บาท ให้คิดภาษี 15%
"""

salary = float(input("Enter Your Salary : "))
overtime = float(input("Enter Your OverTime : "))

total = salary + overtime

if total <= 5000:
  tax = 0
elif total <= 20000:
  tax = total * 0.07
elif total <= 50000:
  tax = total * 0.10
else:
  tax = total * 0.15
income = total - tax

print(f"Taxes to be paid: {tax:.2f} ฿")
print(f"Net Income: {income:.2f} ฿")

"""5.ให้เขียนคำสั่งแสดงผลดังผังงานต่อไปนี้"""

score = int(input("Enter Your Score : "))

if score >= 80 and score <= 100:
    grade = 'A'
elif score >= 70 and score <= 79:
    grade = 'B'
elif score >= 60 and score <= 69:
    grade = 'C'
elif score >= 50 and score <= 59:
    grade = 'D'
elif score >= 0 and score <= 49:
    grade = 'F'
else:
    print("*")
    exit()

if 'grade' in locals():
    print(f"Your Grade : {grade}")
print("Good Bye")

"""6. ให้เขียนโปรแกรมตามผังงานต่อไปนี้"""

print("Menu Program")
print("A : Add")
print("S : Subtract")

menu = input("Enter Your Choice : ")

if menu.lower() == 'a':
    print("Add Program")
    num1 = float(input("Enter Your First Number : "))
    num2 = float(input("Enter Your Second Number : "))
    print(f"Result of {num1} + {num2} = {num1 + num2}")
elif menu.lower() == 's':
    print("Subtract Program")
    num1 = float(input("Enter Your First Number : "))
    num2 = float(input("Enter Your Second Number : "))
    print(f"Result of {num1} - {num2} = {num1 - num2}")
else:
    print("Please Try Again")

"""7. ให้เขียนโปรแกรมตามผังงานต่อไปนี้"""

score = int(input("Enter Your Score : "))
print("Very Good")if score>=80 else print("Sorry")