# -*- coding: utf-8 -*-
"""แบบฝึกหัดครั้งที่ 5.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1u0dgVFtY9Iw3U3YZGzRn55Wbja4hkh1d

1. ให้เขียนโปรแกรมแสดงข้อมูลในลิสต์ โดยกำหนดให้ตัวแปร a เก็บข้อมูลในลิสต์ดังนี้
a = list([99, 5000.75,“Cat”, True])
"""

a = list([99, 5000.75, "Cat", True])
print(a)

"""2. ให้เขียนโปรแกรมแสดงสระในภำษำอังกฤษ เมื่อมีกำรกำหนดลิสต์ดังนี้
vowels = ['a', 'e', 'i', 'o', 'u']
"""

vowels = list(['a', 'e', 'i', 'o', 'u'])

for vowel in vowels:
    print(vowel)

"""3. ให้หำผลลัพธ์ของโปรแกรม สังเกตบรรทัดที่ 3 ต่อไปนี้"""

num = [10,20,30,40,50]
print(num)
num = [i * 2 for i in num]
print(num)

"""4. ให้หำผลลัพธ์ของโปรแกรมตรวจสอบว่ำข้อมูล Python อยู่ในลิสต์หรือไม่"""

program = ["Python", "C", "PHP", "ASP"]
if "Python" in program:
  print("Pthon อยู่ในลิสต์")
else:
  print("Python ไม่อยู่ในลิสต์")

"""5. ให้ใช้ฟังก์ชัน len(), max(), min(),sum(), del() เมื่อก ำหนดลิสต์ num ดังนี้
num = [99,10,20,50,15]
"""

num = [99, 10, 20, 50, 15]

print("จำนวนสมาชิกในลิสต์:", len(num))

print("สมาชิกที่มีค่ามากที่สุด:", max(num))

print("สมาชิกที่มีค่าน้อยที่สุด:", min(num))

print("ผลรวมของสมาชิกทั้งหมด:", sum(num))

del num

""" 6. ให้ใช้ฟังก์ชัน append(), clear(), count(),insert(), remove(), sort(), reverse() เมื่อ
ก ำหนดให้ลิสต์ p = ["Python","C","PHP","ASP"]
"""

p = ["Python", "C", "PHP", "ASP"]

p.append("Java Script")
print("append():", p)

count_python = p.count("Python")
print("จำนวนครั้งที่ 'Python' ปรากฏในลิสต์:", count_python, "ครั้ง")

p.insert(2, "Java")
print("insert():", p)

p.remove("Java")
print("remove():", p)

p.sort()
print("sort():", p)

p.reverse()
print("reverse():", p)

p.clear()
print("clear():", p)

"""7. ให้แสดงผลลัพธ์ของโปรแกรมต่อไปนี้"""

a = (10,2000.75, "Cat", "One")
print(a[0],a[1],a[2],a[3])
# a[2] = "Dog" บรรทัดนี้ผิดพลาดทูเพิลแก้ไขข้อมูลไม่ได้
a[2] = "Dog"
print(a)

L1 = ['a', 'e', 'i', 'o', 'u']
my_tuple = tuple(L1)
for i in my_tuple:
  print(i)
type(L1)
type(my_tuple)

L1 = ["a","e","i","o","u"]
my_tuple = tuple(L1)
print (my_tuple[-5])
print (my_tuple[-4])
print (my_tuple[-3])
print (my_tuple[-2])
print (my_tuple[-1])
print ("Good Bye")

"""8. ให้แสดงผลลัพธ์ของโปรแกรมที่เป็นกำรอัพเดตข้อมูลในลิสต์ แล้วแปลงข้อมูลเป็นทูเพิลต่อไปนี้"""

x = ("apple", "banana", "cherry")
y = list(x)
y[1] = "kiwi"
x = tuple(y)

print(x)

"""9. ให้เขียนโปรแกรมใช้เครื่องหมาย + เมื่อกำหนดให้ A = (10,20,30,40,50) B =('a','b', 'c', 'd',)"""

A = (10,20,30,40,50)
B =('a','b', 'c', 'd',)

result = A + B
print(result)

"""10.ให้เขียนใช้เครื่องหมาย * ทูเพิล 3 เมื่อกำหนดให้
X = (“Hello”,”Python”)
Y = X * 3
"""

X = ("Hello", "Python")
Y = X * 3
print(Y)

"""11. ให้เขียนโปรแกรมรับปี พ.ศ.จำกแป้นพิมพ์แล้วให้เปลี่ยนเป็นเลขไทยแล้วแสดงคำอ่านเรียงคำ
tp_thai_digits = ('๐', '๑', '๒', '๓', '๔', '๕', '๖', '๗', '๘', '๙')
tp_digit_words = ('ศูนย์', 'หนึ่ง', 'สอง', 'สาม', 'สี่', 'ห้า', 'หก', 'เจ็ด','แปด', 'เก้า')
"""

def year_to_thai_words(year):
    tp_thai_digits = ('๐', '๑', '๒', '๓', '๔', '๕', '๖', '๗', '๘', '๙')
    tp_digit_words = ('ศูนย์', 'หนึ่ง', 'สอง', 'สาม', 'สี่', 'ห้า', 'หก', 'เจ็ด', 'แปด', 'เก้า')

    thai_year = ''.join([tp_thai_digits[int(digit)] for digit in str(year)])
    thai_words = ' '.join([tp_digit_words[int(digit)] for digit in thai_year])

    return thai_year, thai_words

year = int(input("กรุณาใส่ปี พ.ศ.: "))
thai_year, thai_words = year_to_thai_words(year)
print(f"เลขไทย: {thai_year}")
print(f"คำอ่าน: {thai_words}")