# -*- coding: utf-8 -*-
"""สอบปฎิบัติครั้งที่ 2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1B3Tlveqdtw4qlovbMFVEM_FUKqDcu3q5

ให้เขียนฟังก์ชัน 3 ฟังก์ชันจากเมนู โดยใช้ลูปทำงานจนกว่าจะกด 9 จึงจะออกจากระบบ
"""

number = 0
is_lists = []
menu_input = ''

def menu():
    print("1. ป้อนตัวเลขแสดงจำนวนเต็ม")
    print("2. เรียงข้อมูลจากมากไปน้อย")
    print("3. แสดงข้อมูลในลิสต์")
    print("9. ออกจากโปรแกรม")

    global menu_input
    menu_input = input("Select Menu: ")

    if menu_input == '1':
        insert_list()
    elif menu_input == '2':
        show_list_sort()
    elif menu_input == '3':
        show_data_list()
    elif menu_input == '9':
        print("ออกจากโปรแกรมแล้วครับ")
    else:
        print("โปรดลองใหม่อีกครั้ง")

def insert_list():
    global number
    number = int(input("ป้อนตัวเลข: "))
    is_lists.append(number)

def show_list_sort():
    sorted_list = sorted(is_lists, reverse=True)
    print(sorted_list)

def show_data_list():
    print(is_lists)

while True:
    menu()
    if menu_input == '9':
        break